schema:
  wizard:
    context: ${SW_CONTEXT:}
    database:
      connection-url: jdbc:postgresql://${DS_HOST:localhost}:${DS_PORT:5432}/${DS_DATABASE:schema_wizard}
      username: postgres
      password: root
    migration:
      package-name: com.example.migration
    extension:
      package-name: com.example.extension
    log:
      sql-query: ${LOG_GENERATED_SQL:true}
    defaults:
      text:
        max-length: ${DEFAULT_MAX_LENGTH:255}