package org.schemawizard.core.dao.impl;

import org.schemawizard.core.dao.HistoryTableQueryFactory;

import static org.schemawizard.core.dao.Constants.APPLIED_ON;
import static org.schemawizard.core.dao.Constants.DESCRIPTION;
import static org.schemawizard.core.dao.Constants.ID;
import static org.schemawizard.core.dao.Constants.MIGRATION_TABLE_NAME;
import static org.schemawizard.core.dao.Constants.VERSION;

public class OracleHistoryTableQueryFactory implements HistoryTableQueryFactory {
    @Override
    public String getCreateMigrationHistoryTableSql() {
        return String.format("CREATE TABLE %s ("
                        + "%s NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, "
                        + "%s INTEGER NOT NULL, "
                        + "%s VARCHAR2(255) NOT NULL, "
                        + "%s TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)",
                MIGRATION_TABLE_NAME, ID, VERSION, DESCRIPTION, APPLIED_ON);
    }

    @Override
    public String getSelectTableSql() {
        return String.format("SELECT table_name "
                        + "FROM USER_TABLES "
                        + "WHERE LOWER(table_name)='%s'",
                MIGRATION_TABLE_NAME);
    }

    @Override
    public String getSelectMigrationsSql() {
        return String.format("SELECT %s, %s, %s, %s "
                        + "FROM %s order by version",
                ID, VERSION, DESCRIPTION, APPLIED_ON,
                MIGRATION_TABLE_NAME);
    }

    @Override
    public String getInsertMigrationHistoryRowQuery() {
        return String.format(
                "INSERT INTO %s (%s, %s) VALUES (?, ?)",
                MIGRATION_TABLE_NAME,
                VERSION,
                DESCRIPTION);
    }
}
