name: Release library

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Release type
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get latest version
        id: latest_version
        run: |
          chmod +x ./.github/scripts/get_latest_git_tag.sh
          latest_version=$(./.github/scripts/get_latest_git_tag.sh)
          echo "Latest version is: $latest_version"
          echo "value=$latest_version" >> $GITHUB_OUTPUT

      - name: Generate next version
        id: next_version
        run: |
          chmod +x ./.github/scripts/increment_version.sh
          next_version=$(./.github/scripts/increment_version.sh ${{ steps.latest_version.outputs.value }} ${{ github.event.inputs.release_type }})
          echo "${{ steps.latest_version.outputs.value }} -> $next_version"
          echo "next_version=$next_version" >> $GITHUB_OUTPUT
      
